from simple_enum import SimpleEnum
from panel.utils.language_enum import LANG_ENUM


class LANG_STR_ENUM(SimpleEnum):
    UI_APPLY = None
    UI_CANCEL = None
    UI_WARNING = None
    UI_APP_TITLE = None
    ERROR_HOU_PATH = None
    ERROR_HOU_PATH_SETTINGS = None
    ERROR_PYLIB_PATH = None
    ERROR_TITLE = None
    ERROR_INVALID_FILE_PATH = None
    UI_MENU_FILE = None
    UI_MENU_FILE_OPEN_HDA = None
    UI_MENU_FILE_OPEN_HDA_FILE_DIALOG_TITLE = None
    UI_MENU_FILE_OPEN_HIP = None
    UI_MENU_FILE_OPEN_HIP_FILE_DIALOG_TITLE = None
    UI_MENU_FILE_OPEN_RECENT = None
    UI_MENU_FILE_SAVE_HIP = None
    UI_MENU_FILE_SAVE_HIP_FILE_DIALOG_TITLE = None
    UI_MENU_SETTINGS = None
    UI_MENU_SETTINGS_SAVE = None
    UI_MENU_SETTINGS_GENERAL = None
    UI_MENU_SETTINGS_HOUDINI_ROOT = None
    UI_MENU_SETTINGS_LANGUAGE = None
    UI_MENU_SETTINGS_LANGUAGE_EN_US = None
    UI_MENU_SETTINGS_LANGUAGE_ZH_CN = None
    UI_MENU_HELP = None
    UI_MENU_HELP_PROJECT_URL = None
    UI_MENU_HELP_UPDATE = None
    UI_MENU_HELP_UPDATE_TITLE = None
    UI_MENU_HELP_UPDATE_WARNING = None
    UI_MENU_HELP_UPDATE_BUTTON = None
    UI_MENU_HELP_UPDATE_ERROR_SERVER_CONNECTION = None
    UI_MENU_HELP_UPDATE_ERROR_DOWNLOAD_ERROR = None
    UI_MENU_WINDOW = None
    UI_MENU_WINDOW_MESH_VIEWER = None
    UI_MESH_VIEWER_OPTIONS_PANEL = None
    UI_MESH_VIEWER_OPTIONS_PANEL_VERTEX_COLOR = None
    UI_MESH_VIEWER_OPTIONS_PANEL_ADJUST_CAMERA = None
    UI_MESH_VIEWER_OPTIONS_PANEL_AUTO_UPDATE_NODE = None
    UI_MESH_VIEWER_OPTIONS_PANEL_DISPLAY_AXIS_GRID = None
    UI_MESH_VIEWER_INFO_VERTEX = None
    UI_MESH_VIEWER_INFO_POLYGON = None
    UI_TWIRL_EXPANSION_DESCRIPTION = None
    UI_TWIRL_COLLAPSE_DESCRIPTION = None
    UI_COOK_TITLE = None
    UI_COOK_TIME_LABEL = None
    UI_HDAPANEL_EMPTY_HDA = None
    UI_HDAPANEL_AUTO_RECOOK = None
    UI_HDAPANEL_FORCE_RECOOK = None
    UI_HDAPANEL_BATCH_LABEL = None
    UI_HDAPANEL_BATCH_BUTTON = None
    UI_BATCHPANEL_TITLE = None
    UI_BATCHPANEL_INDEX = None
    UI_BATCHPANEL_VALUE = None
    UI_BATCHPANEL_CLEAR = None
    UI_BATCHPANEL_IMPORT = None
    UI_BATCHPANEL_INHERIT = None
    UI_BATCHPANEL_SELECT_REMOVE_ROW = None
    UI_BATCHPANEL_BUTTON_TOOLTIP = None
    # 连接相关
    UI_CONNECTION_MENU = None
    UI_CONNECTION_STATUS_CONNECTED = None
    UI_CONNECTION_STATUS_DISCONNECTED = None
    UI_CONNECTION_QUICK_CONNECT = None
    UI_CONNECTION_DISCONNECT = None
    UI_CONNECTION_START_LOCAL_SERVER = None
    UI_CONNECTION_STOP_LOCAL_SERVER = None
    UI_CONNECTION_SETTINGS = None
    UI_CONNECTION_DIALOG_TITLE = None
    UI_CONNECTION_GROUP_TITLE = None
    UI_CONNECTION_HOST = None
    UI_CONNECTION_PORT = None
    UI_CONNECTION_TIMEOUT = None
    UI_CONNECTION_AUTO_RECONNECT = None
    UI_CONNECTION_RETRY_INTERVAL = None
    UI_CONNECTION_MAX_RETRIES = None
    UI_CONNECTION_START_LOCAL_SERVER_CHECKBOX = None
    UI_CONNECTION_AUTO_CONNECT_CHECKBOX = None
    UI_CONNECTION_STATUS_GROUP_TITLE = None
    UI_CONNECTION_STATUS_LABEL = None
    UI_CONNECTION_LOG_LABEL = None
    UI_CONNECTION_CONNECT_BUTTON = None
    UI_CONNECTION_DISCONNECT_BUTTON = None
    UI_CONNECTION_SAVE_BUTTON = None
    UI_CONNECTION_CANCEL_BUTTON = None
    UI_CONNECTION_CONNECTING = None
    UI_CONNECTION_ERROR_NO_HOST = None
    UI_CONNECTION_ERROR_CONFIG_HOST = None
    UI_CONNECTION_LOG_CONNECTING = None
    UI_CONNECTION_LOG_SUCCESS = None
    UI_CONNECTION_LOG_DISCONNECTED = None
    UI_CONNECTION_LOG_ERROR = None
    UI_CONNECTION_LOG_STARTING_SERVER = None
    UI_CONNECTION_LOG_SERVER_STARTED = None
    UI_CONNECTION_LOG_STOPPING_SERVER = None
    UI_CONNECTION_LOG_SERVER_STOPPED = None
    UI_CONNECTION_LOG_SETTINGS_SAVED = None
    UI_CONNECTION_SERVER_INFO_NONE = None
    UI_CONNECTION_LOCAL_SERVER_NOT_STARTED = None
    UI_CONNECTION_LOCAL_SERVER_RUNNING = None


LANG_MAP = {LANG_STR_ENUM.UI_APPLY: {LANG_ENUM.EN_US: "Apply", LANG_ENUM.ZH_CN: "应用"},
            LANG_STR_ENUM.UI_CANCEL: {LANG_ENUM.EN_US: "Cancel", LANG_ENUM.ZH_CN: "取消"},
            LANG_STR_ENUM.UI_WARNING: {LANG_ENUM.EN_US: "Warning", LANG_ENUM.ZH_CN: "警告"},
            LANG_STR_ENUM.ERROR_HOU_PATH: {LANG_ENUM.EN_US: "Houdini path not exist.", LANG_ENUM.ZH_CN: "Houdini路径不存在"},
            LANG_STR_ENUM.ERROR_HOU_PATH_SETTINGS: {LANG_ENUM.EN_US: "Houdini path not exist, please click Settings>General Settings to set.", LANG_ENUM.ZH_CN: "Houdini路径不存在，请点击设置>常规设置进行设置"},
            LANG_STR_ENUM.ERROR_TITLE: {LANG_ENUM.EN_US: "Error", LANG_ENUM.ZH_CN: "错误"},
            LANG_STR_ENUM.ERROR_INVALID_FILE_PATH: {LANG_ENUM.EN_US: "Invalid File Path", LANG_ENUM.ZH_CN: "无效的文件路径"},
            LANG_STR_ENUM.UI_APP_TITLE: {LANG_ENUM.EN_US: "Portable Houdini", LANG_ENUM.ZH_CN: "Portable Houdini"},
            LANG_STR_ENUM.ERROR_PYLIB_PATH: {LANG_ENUM.EN_US: "Houdini pylib path not exist.", LANG_ENUM.ZH_CN: "Houdini Pylib路径不存在"},
            LANG_STR_ENUM.UI_MENU_FILE: {LANG_ENUM.EN_US: "File", LANG_ENUM.ZH_CN: "文件"},
            LANG_STR_ENUM.UI_MENU_FILE_OPEN_HDA: {LANG_ENUM.EN_US: "Open HDA", LANG_ENUM.ZH_CN: "打开HDA"},
            LANG_STR_ENUM.UI_MENU_FILE_OPEN_HDA_FILE_DIALOG_TITLE: {LANG_ENUM.EN_US: "Open HDA File", LANG_ENUM.ZH_CN: "打开HDA文件"},
            LANG_STR_ENUM.UI_MENU_FILE_OPEN_HIP: {LANG_ENUM.EN_US: "Open HIP", LANG_ENUM.ZH_CN: "打开HIP"},
            LANG_STR_ENUM.UI_MENU_FILE_OPEN_HIP_FILE_DIALOG_TITLE: {LANG_ENUM.EN_US: "Open HIP File", LANG_ENUM.ZH_CN: "打开HIP文件"},
            LANG_STR_ENUM.UI_MENU_FILE_OPEN_RECENT: {LANG_ENUM.EN_US: "Open Recent File", LANG_ENUM.ZH_CN: "打开最近文件"},
            LANG_STR_ENUM.UI_MENU_FILE_SAVE_HIP: {LANG_ENUM.EN_US: "Save debug HIP File", LANG_ENUM.ZH_CN: "保存debug hip文件"},
            LANG_STR_ENUM.UI_MENU_FILE_SAVE_HIP_FILE_DIALOG_TITLE: {LANG_ENUM.EN_US: "Save debug HIP File", LANG_ENUM.ZH_CN: "保存debug hip文件"},
            LANG_STR_ENUM.UI_MENU_SETTINGS: {LANG_ENUM.EN_US: "Settings", LANG_ENUM.ZH_CN: "设置"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_SAVE: {LANG_ENUM.EN_US: "Save Settings", LANG_ENUM.ZH_CN: "保存设置"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_GENERAL: {LANG_ENUM.EN_US: "General Settings", LANG_ENUM.ZH_CN: "常规设置"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_HOUDINI_ROOT: {LANG_ENUM.EN_US: "Houdini Root", LANG_ENUM.ZH_CN: "Houdini根目录"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_LANGUAGE: {LANG_ENUM.EN_US: "Language", LANG_ENUM.ZH_CN: "语言"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_LANGUAGE_EN_US: {LANG_ENUM.EN_US: "English", LANG_ENUM.ZH_CN: "English"},
            LANG_STR_ENUM.UI_MENU_SETTINGS_LANGUAGE_ZH_CN: {LANG_ENUM.EN_US: "中文", LANG_ENUM.ZH_CN: "中文"},
            LANG_STR_ENUM.UI_MENU_HELP: {LANG_ENUM.EN_US: "Help", LANG_ENUM.ZH_CN: "帮助"},
            LANG_STR_ENUM.UI_MENU_HELP_PROJECT_URL: {LANG_ENUM.EN_US: "Project Link", LANG_ENUM.ZH_CN: "项目链接"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE: {LANG_ENUM.EN_US: "Update", LANG_ENUM.ZH_CN: "更新"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE_TITLE: {LANG_ENUM.EN_US: "Update Application", LANG_ENUM.ZH_CN: "更新应用"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE_WARNING: {LANG_ENUM.EN_US: "Clicking the update button will forcibly clear all files of the current tool\nIf you have modified any source files locally, please back them up promptly\nThe software will exit after the update is complete.", LANG_ENUM.ZH_CN: "点击更新按钮后将会强制清除当前工具的所有文件\n如在本地有修改源文件请及时备份\n更新完成后会退出软件。"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE_BUTTON: {LANG_ENUM.EN_US: "Force Update", LANG_ENUM.ZH_CN: "强制更新"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE_ERROR_SERVER_CONNECTION: {LANG_ENUM.EN_US: "Failed to connect to server!", LANG_ENUM.ZH_CN: "连接服务器失败！"},
            LANG_STR_ENUM.UI_MENU_HELP_UPDATE_ERROR_DOWNLOAD_ERROR: {LANG_ENUM.EN_US: "Encounter some errors when downloading!", LANG_ENUM.ZH_CN: "下载过程中发生错误！"},
            LANG_STR_ENUM.UI_MENU_WINDOW: {LANG_ENUM.EN_US: "Window", LANG_ENUM.ZH_CN: "窗口"},
            LANG_STR_ENUM.UI_MENU_WINDOW_MESH_VIEWER: {LANG_ENUM.EN_US: "Mesh Viewer", LANG_ENUM.ZH_CN: "模型预览窗口"},
            LANG_STR_ENUM.UI_MESH_VIEWER_OPTIONS_PANEL: {LANG_ENUM.EN_US: "Options", LANG_ENUM.ZH_CN: "选项"},
            LANG_STR_ENUM.UI_MESH_VIEWER_OPTIONS_PANEL_ADJUST_CAMERA: {LANG_ENUM.EN_US: "Auto Move Camera", LANG_ENUM.ZH_CN: "自动回正摄像机"},
            LANG_STR_ENUM.UI_MESH_VIEWER_OPTIONS_PANEL_VERTEX_COLOR: {LANG_ENUM.EN_US: "Display Vertex Color", LANG_ENUM.ZH_CN: "显示顶点色"},
            LANG_STR_ENUM.UI_MESH_VIEWER_OPTIONS_PANEL_AUTO_UPDATE_NODE: {LANG_ENUM.EN_US: "Auto Update Model", LANG_ENUM.ZH_CN: "自动更新模型"},
            LANG_STR_ENUM.UI_MESH_VIEWER_OPTIONS_PANEL_DISPLAY_AXIS_GRID: {LANG_ENUM.EN_US: "Display Axis Grid", LANG_ENUM.ZH_CN: "显示坐标平面"},
            LANG_STR_ENUM.UI_MESH_VIEWER_INFO_VERTEX: {LANG_ENUM.EN_US: "Vertices", LANG_ENUM.ZH_CN: "顶点数"},
            LANG_STR_ENUM.UI_MESH_VIEWER_INFO_POLYGON: {LANG_ENUM.EN_US: "Triangles", LANG_ENUM.ZH_CN: "三角面数"},
            LANG_STR_ENUM.UI_HDAPANEL_EMPTY_HDA: {LANG_ENUM.EN_US: "Select a HDA", LANG_ENUM.ZH_CN: "打开一个HDA"},
            LANG_STR_ENUM.UI_HDAPANEL_AUTO_RECOOK: {LANG_ENUM.EN_US: "Auto Recook", LANG_ENUM.ZH_CN: "自动计算"},
            LANG_STR_ENUM.UI_HDAPANEL_FORCE_RECOOK: {LANG_ENUM.EN_US: "Force Recook", LANG_ENUM.ZH_CN: "强制重新计算"},
            LANG_STR_ENUM.UI_HDAPANEL_BATCH_LABEL: {LANG_ENUM.EN_US: "Batches: ", LANG_ENUM.ZH_CN: "批处理数: "},
            LANG_STR_ENUM.UI_HDAPANEL_BATCH_BUTTON: {LANG_ENUM.EN_US: "Batching", LANG_ENUM.ZH_CN: "批处理"},
            LANG_STR_ENUM.UI_TWIRL_EXPANSION_DESCRIPTION: {LANG_ENUM.EN_US: "⇓Click to Expand Batching/Recook settings⇓", LANG_ENUM.ZH_CN: "⇓点击展开批处理/重计算设置⇓"},
            LANG_STR_ENUM.UI_TWIRL_COLLAPSE_DESCRIPTION: {LANG_ENUM.EN_US: "⇑Click to Collapse Batching/Recook settings⇑", LANG_ENUM.ZH_CN: "⇑点击收起批处理/重计算设置⇑"},
            LANG_STR_ENUM.UI_COOK_TITLE: {LANG_ENUM.EN_US: "Cooking", LANG_ENUM.ZH_CN: "计算中"},
            LANG_STR_ENUM.UI_COOK_TIME_LABEL: {LANG_ENUM.EN_US: "Time: ", LANG_ENUM.ZH_CN: "时间: "},
            LANG_STR_ENUM.UI_BATCHPANEL_TITLE: {LANG_ENUM.EN_US: "Batch", LANG_ENUM.ZH_CN: "批处理"},
            LANG_STR_ENUM.UI_BATCHPANEL_INDEX: {LANG_ENUM.EN_US: "Batch Index", LANG_ENUM.ZH_CN: "批次"},
            LANG_STR_ENUM.UI_BATCHPANEL_VALUE: {LANG_ENUM.EN_US: "Value", LANG_ENUM.ZH_CN: "属性值"},
            LANG_STR_ENUM.UI_BATCHPANEL_CLEAR: {LANG_ENUM.EN_US: "Clear", LANG_ENUM.ZH_CN: "清空"},
            LANG_STR_ENUM.UI_BATCHPANEL_IMPORT: {LANG_ENUM.EN_US: "Import", LANG_ENUM.ZH_CN: "导入"},
            LANG_STR_ENUM.UI_BATCHPANEL_INHERIT: {LANG_ENUM.EN_US: "--Inherit Last Row--", LANG_ENUM.ZH_CN: "--继承上行参数--"},
            LANG_STR_ENUM.UI_BATCHPANEL_SELECT_REMOVE_ROW: {LANG_ENUM.EN_US: "Select the row to delete", LANG_ENUM.ZH_CN: "选择需要删除的项"},
            LANG_STR_ENUM.UI_BATCHPANEL_BUTTON_TOOLTIP: {LANG_ENUM.EN_US: "Selected indicates that a click event will be triggered", LANG_ENUM.ZH_CN: "选中表示会触发点击事件"},
            # 连接相关翻译
            LANG_STR_ENUM.UI_CONNECTION_MENU: {LANG_ENUM.EN_US: "Connection", LANG_ENUM.ZH_CN: "连接"},
            LANG_STR_ENUM.UI_CONNECTION_STATUS_CONNECTED: {LANG_ENUM.EN_US: "🟢 Connected", LANG_ENUM.ZH_CN: "🟢 已连接"},
            LANG_STR_ENUM.UI_CONNECTION_STATUS_DISCONNECTED: {LANG_ENUM.EN_US: "🔴 Disconnected", LANG_ENUM.ZH_CN: "🔴 未连接"},
            LANG_STR_ENUM.UI_CONNECTION_QUICK_CONNECT: {LANG_ENUM.EN_US: "Quick Connect", LANG_ENUM.ZH_CN: "快速连接"},
            LANG_STR_ENUM.UI_CONNECTION_DISCONNECT: {LANG_ENUM.EN_US: "Disconnect", LANG_ENUM.ZH_CN: "断开连接"},
            LANG_STR_ENUM.UI_CONNECTION_START_LOCAL_SERVER: {LANG_ENUM.EN_US: "Start Local Server", LANG_ENUM.ZH_CN: "启动本地服务器"},
            LANG_STR_ENUM.UI_CONNECTION_STOP_LOCAL_SERVER: {LANG_ENUM.EN_US: "Stop Local Server", LANG_ENUM.ZH_CN: "停止本地服务器"},
            LANG_STR_ENUM.UI_CONNECTION_SETTINGS: {LANG_ENUM.EN_US: "Connection Settings...", LANG_ENUM.ZH_CN: "连接设置..."},
            LANG_STR_ENUM.UI_CONNECTION_DIALOG_TITLE: {LANG_ENUM.EN_US: "Server Connection Settings", LANG_ENUM.ZH_CN: "服务器连接设置"},
            LANG_STR_ENUM.UI_CONNECTION_GROUP_TITLE: {LANG_ENUM.EN_US: "Connection Settings", LANG_ENUM.ZH_CN: "连接设置"},
            LANG_STR_ENUM.UI_CONNECTION_HOST: {LANG_ENUM.EN_US: "Server Address:", LANG_ENUM.ZH_CN: "服务器地址:"},
            LANG_STR_ENUM.UI_CONNECTION_PORT: {LANG_ENUM.EN_US: "Port:", LANG_ENUM.ZH_CN: "端口:"},
            LANG_STR_ENUM.UI_CONNECTION_TIMEOUT: {LANG_ENUM.EN_US: "Connection Timeout (seconds):", LANG_ENUM.ZH_CN: "连接超时(秒):"},
            LANG_STR_ENUM.UI_CONNECTION_AUTO_RECONNECT: {LANG_ENUM.EN_US: "Auto Reconnect", LANG_ENUM.ZH_CN: "自动重连"},
            LANG_STR_ENUM.UI_CONNECTION_RETRY_INTERVAL: {LANG_ENUM.EN_US: "Retry Interval (seconds):", LANG_ENUM.ZH_CN: "重连间隔(秒):"},
            LANG_STR_ENUM.UI_CONNECTION_MAX_RETRIES: {LANG_ENUM.EN_US: "Max Retries:", LANG_ENUM.ZH_CN: "最大重试次数:"},
            LANG_STR_ENUM.UI_CONNECTION_START_LOCAL_SERVER_CHECKBOX: {LANG_ENUM.EN_US: "Start Local Server", LANG_ENUM.ZH_CN: "启动本地服务器"},
            LANG_STR_ENUM.UI_CONNECTION_AUTO_CONNECT_CHECKBOX: {LANG_ENUM.EN_US: "Auto Connect on Startup", LANG_ENUM.ZH_CN: "启动时自动连接"},
            LANG_STR_ENUM.UI_CONNECTION_STATUS_GROUP_TITLE: {LANG_ENUM.EN_US: "Connection Status", LANG_ENUM.ZH_CN: "连接状态"},
            LANG_STR_ENUM.UI_CONNECTION_STATUS_LABEL: {LANG_ENUM.EN_US: "Status:", LANG_ENUM.ZH_CN: "状态:"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_LABEL: {LANG_ENUM.EN_US: "Connection Log:", LANG_ENUM.ZH_CN: "连接日志:"},
            LANG_STR_ENUM.UI_CONNECTION_CONNECT_BUTTON: {LANG_ENUM.EN_US: "Connect", LANG_ENUM.ZH_CN: "连接"},
            LANG_STR_ENUM.UI_CONNECTION_DISCONNECT_BUTTON: {LANG_ENUM.EN_US: "Disconnect", LANG_ENUM.ZH_CN: "断开连接"},
            LANG_STR_ENUM.UI_CONNECTION_SAVE_BUTTON: {LANG_ENUM.EN_US: "Save Settings", LANG_ENUM.ZH_CN: "保存设置"},
            LANG_STR_ENUM.UI_CONNECTION_CANCEL_BUTTON: {LANG_ENUM.EN_US: "Cancel", LANG_ENUM.ZH_CN: "取消"},
            LANG_STR_ENUM.UI_CONNECTION_CONNECTING: {LANG_ENUM.EN_US: "Connecting...", LANG_ENUM.ZH_CN: "连接中..."},
            LANG_STR_ENUM.UI_CONNECTION_ERROR_NO_HOST: {LANG_ENUM.EN_US: "Error: Please enter server address", LANG_ENUM.ZH_CN: "错误: 请输入服务器地址"},
            LANG_STR_ENUM.UI_CONNECTION_ERROR_CONFIG_HOST: {LANG_ENUM.EN_US: "Please configure server address in connection settings first", LANG_ENUM.ZH_CN: "请先在连接设置中配置服务器地址"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_CONNECTING: {LANG_ENUM.EN_US: "Connecting to", LANG_ENUM.ZH_CN: "正在连接到"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_SUCCESS: {LANG_ENUM.EN_US: "Connection successful", LANG_ENUM.ZH_CN: "连接成功"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_DISCONNECTED: {LANG_ENUM.EN_US: "Connection disconnected", LANG_ENUM.ZH_CN: "连接断开"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_ERROR: {LANG_ENUM.EN_US: "Connection error", LANG_ENUM.ZH_CN: "连接错误"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_STARTING_SERVER: {LANG_ENUM.EN_US: "Starting local Houdini server...", LANG_ENUM.ZH_CN: "正在启动本地 Houdini 服务器..."},
            LANG_STR_ENUM.UI_CONNECTION_LOG_SERVER_STARTED: {LANG_ENUM.EN_US: "Local server started successfully", LANG_ENUM.ZH_CN: "本地服务器启动成功"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_STOPPING_SERVER: {LANG_ENUM.EN_US: "Stopping local server...", LANG_ENUM.ZH_CN: "正在停止本地服务器..."},
            LANG_STR_ENUM.UI_CONNECTION_LOG_SERVER_STOPPED: {LANG_ENUM.EN_US: "Local server stopped", LANG_ENUM.ZH_CN: "本地服务器已停止"},
            LANG_STR_ENUM.UI_CONNECTION_LOG_SETTINGS_SAVED: {LANG_ENUM.EN_US: "Settings saved", LANG_ENUM.ZH_CN: "设置已保存"},
            LANG_STR_ENUM.UI_CONNECTION_SERVER_INFO_NONE: {LANG_ENUM.EN_US: "No server information", LANG_ENUM.ZH_CN: "无服务器信息"},
            LANG_STR_ENUM.UI_CONNECTION_LOCAL_SERVER_NOT_STARTED: {LANG_ENUM.EN_US: "Local server: Not started", LANG_ENUM.ZH_CN: "本地服务器: 未启动"},
            LANG_STR_ENUM.UI_CONNECTION_LOCAL_SERVER_RUNNING: {LANG_ENUM.EN_US: "Local server: Running", LANG_ENUM.ZH_CN: "本地服务器: 运行中"},
            }


def getLocalizationStr(str_enum, lang_enum=None):
    if lang_enum is None:
        from globals import LANGUAGE
        lang_enum = LANGUAGE

    if LANG_MAP.__contains__(str_enum):
        if LANG_MAP[str_enum].__contains__(lang_enum):
            return LANG_MAP[str_enum][lang_enum]

    return ""
